name: CD

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

env:
  javascript-root: 'pysvelte'

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
    - name: Pytest
      run: pytest

  javascript:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn install
      working-directory: ${{env.javascript-root}}
    - name: Jest
      run: yarn test
      working-directory: ${{env.javascript-root}}
    - name: Lint
      run: yarn lint
      working-directory: ${{env.javascript-root}}
    - name: Check types
      run: yarn tsc --noEmit
      working-directory: ${{env.javascript-root}}
