name: Checks

on:
  push:
    branches: 
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
  pull_request:
    branches: 
      - main
    paths-ignore:
      - '.devcontainer/**'
      - '.github/**'
      - '.vscode/**'
      - '.gitignore'
      - 'README.md'
  # Allow this workflow to be called from other workflows
  workflow_call:
    inputs:
      #  Requires at least one input to be valid, but in practice we don't need any
      dummy:
        type: string
        required: false

jobs:
  python-checks:
    name: Python Checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
    env:
      working-directory: python
    defaults:
      run:
        working-directory: python
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install --with dev
    - name: Pytest
      run: poetry run pytest
    - name: Type check
      run: poetry run mypy circuitsvis
    - name: Build check
      run: poetry build

  react-checks:
    name: React checks
    runs-on: ubuntu-latest
    env:
      working-directory: react
    defaults:
      run:
        working-directory: react
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: yarn
    - name: Jest
      run: yarn test
    - name: Lint
      run: yarn lint
    - name: Check types
      run: yarn typeCheck
    - name: Build check
      run: yarn build
