name: Python

on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master

env:
  working-directory: 'pysvelte'

jobs:
  test:
    name: Test, Type Check & Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
      working-directory: ${{env.working-directory}}
    - name: Pytest
      run: pytest
      working-directory: ${{env.working-directory}}
